version: '3.8'

services:
  backend:
    build: './backend'
    ports:
      - "3001:3001"             
    env_file: ./backend/.env    
    volumes:
      - ./backend:/app          
    networks:
      - app-network             
    environment:
      - PORT=3001

  frontend:
    build: './frontend'
    ports:
      - "5173:5173"             
    depends_on:
      - backend                 
    volumes:
      - ./frontend:/app         
    networks:
      - app-network             
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_PORT=5173

networks:
  app-network:
    driver: bridge
